In [4]:
import numpy as np

In [40]:
class Vectors:
    def __init__(self, *args):
        self.list = args

    def vectorizer(self):
        vctr = np.array(self.list)
        return vctr


In [42]:
v = Vectors([1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5])
vector = v.vectorizer()
print(str(vector))

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [49]:
vc1 = Vectors(1, 2, 3, 4, 5).vectorizer()
vc2 = Vectors(1, 2, 3, 4, 0).vectorizer()
sum = vc1 + vc2
print(str(sum))

[2 4 6 8 5]


In [50]:
substraction = vc1 - vc2
print(str(substraction))

[0 0 0 0 5]


In [53]:
dot_product = np.dot(vc1, vc2)
print(str(dot_product))

30


In [52]:
magnitute1 = np.linalg.norm(vc1)
magnitute2 = np.linalg.norm(vc2)
print(str(magnitute1), str(magnitute2))

7.416198487095663 5.477225575051661


In [55]:
if magnitute1 != 0 :
    normalized_vector = vc1 / magnitute1
    print(str(normalized_vector))
else :
    print(str(normalized_vector))     

[0.13483997 0.26967994 0.40451992 0.53935989 0.67419986]
